import React from 'react'
import { motion as Motion } from 'framer-motion'
import { ArrowRight } from 'lucide-react'
import HeroBackgroundCanvas from '../components/HeroBackgroundCanvas'
import { useSEO } from '../hooks/useSEO'
import './HomePage.css'

function HomePage() {
  useSEO({
    title: 'TSH Website Previews',
    description:
      'Preview websites created by That Software House for outreach, concepts, and modern redesign proposals.',
    canonicalUrl: 'https://preview.thatsoftwarehouse.com/',
    openGraph: {
      title: 'TSH Website Previews',
      description:
        'Custom website previews generated by That Software House for modern redesign proposals.',
      url: 'https://preview.thatsoftwarehouse.com/',
    },
  })

  return (
    <main className="preview-home">
      <div className="preview-home__backdrop" aria-hidden="true">
        <HeroBackgroundCanvas />
        <div className="preview-home__grain" />
      </div>

      <Motion.section
        className="preview-home__content"
        initial={{ opacity: 0, y: 16 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.8, ease: [0.22, 1, 0.36, 1] }}
      >
        <p className="preview-home__eyebrow">TSH Preview Hub</p>
        <h1>A client preview website created by That Software House</h1>
        <a
          href="https://thatsoftwarehouse.com"
          className="preview-home__cta"
          target="_blank"
          rel="noreferrer"
        >
          Check us out
          <ArrowRight size={18} />
        </a>
      </Motion.section>
    </main>
  )
}

export default HomePage
